steps:
  # Install App
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
    dir: "frontend"
  # Test App
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "lint"]
    dir: "frontend"
  # Build App
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "frontend"

  # Install Functions
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
    dir: "frontend/functions"

  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    dir: "frontend"
    args:
      [
        "deploy",
        "--debug",
        "--token",
        "1//06uzfE8LaTFpkCgYIARAAGAYSNwF-L9Ir3UKhYZoF4r7O8X7vlR8dNa_xX2NRml4JYcW-uv2p2374xsBkYy7ArVJtCC1CRs13brs",
      ]
timeout: "900s"
